spring.application.name=client-java

# Configuración JTA Atomikos
spring.jta.atomikos.properties.default-jta-timeout=300000
spring.jta.atomikos.properties.max-timeout=300000
spring.jta.atomikos.properties.enable-logging=true
spring.jta.atomikos.datasource.max-pool-size=25
spring.jta.atomikos.datasource.min-pool-size=3
spring.jta.atomikos.datasource.max-lifetime=20000
spring.jta.atomikos.datasource.borrow-connection-timeout=30

# Datasource Inventario
spring.datasource.inventario.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
spring.datasource.inventario.xa-properties.url=jdbc:mysql://localhost:3306/inventario?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&defaultAuthenticationPlugin=mysql_native_password
spring.datasource.inventario.xa-properties.user=equipo
spring.datasource.inventario.xa-properties.password=123456
spring.datasource.inventario.unique-resource-name=inventarioDB

# Datasource Facturación
spring.datasource.facturacion.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
spring.datasource.facturacion.xa-properties.url=jdbc:mysql://localhost:3307/facturacion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&defaultAuthenticationPlugin=mysql_native_password
spring.datasource.facturacion.xa-properties.user=equipo
spring.datasource.facturacion.xa-properties.password=123456
spring.datasource.facturacion.unique-resource-name=facturacionDB

# Datasource Pagos
spring.datasource.pagos.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
spring.datasource.pagos.xa-properties.url=jdbc:mysql://localhost:3308/pagos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&defaultAuthenticationPlugin=mysql_native_password
spring.datasource.pagos.xa-properties.user=equipo
spring.datasource.pagos.xa-properties.password=123456
spring.datasource.pagos.unique-resource-name=pagosDB

# JPA Global
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# Server
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JSON encoding
spring.jackson.encoding.charset=UTF-8
spring.jackson.default-property-inclusion=non_null
