# Server Configuration
server.port=8082

# Application Configuration
spring.application.name=proveedor-b-app

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=proveedor-b-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true

# Logging Configuration
logging.level.proveedor=INFO