# Server Configuration
server.port=8081

# Application Configuration
spring.application.name=proveedor-a-app

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=proveedor-a-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true

# Logging Configuration
logging.level.proveedor=INFO